### ISSUE TITLE
Composer branch alias

### ISSUE THREAD

**Issue by benji07** [antidot/PHP_API#25]
Could you add a branch alias in your composer.json file ?

So I can require antidot/php_api: 0.16.*

https://getcomposer.org/doc/articles/aliases.md

**Comment by charlthibault** [comment]
Hi, 

I'v just done it. As old branches tags pattern were vx.x.x. this doesn't works out of the boxe, so I put a new tag 0.16.4 for last version. Next versions will be tag without 'v'

**Comment by benji07** [comment]
No need to change your tags format (look what symfony is doing).

But you also need to enable the hook in GitHub to automatically push new information to packagist 

Envoyé de mon iPhone

**Comment by charlthibault** [comment]
The packagist webhook is already enabled

**Comment by benji07** [comment]
Weird, I don't see the branch alias information on it https://packagist.org/packages/antidot/php_api#dev-master

**Comment by charlthibault** [comment]
Ok, we have some issue to get the hook working as expected. Waiting to solve this, we manually update on packagist side.
