### ISSUE TITLE
Trouble with afs:filter

### ISSUE THREAD

**Issue by benji07** [antidot/PHP_API#29]
Hey, I tried to add a default filter inside my query:
```php 
$query = AfsQuery::create_from_parameters([
    'query' => $query,
    'locale' => 'fr_BE',
    'page' => $page,
    'replies' => $perPage,
    'filter' => [
        'store' => 'myStoreId'
    ]
]);

return $this->connector->execute($query, AfsHelperFormat::HELPERS);
```
But doesn't work, until i change it to:
```php
'store' => ['"myStoreId"']
```

Do you know if there is an other way to do this ?

**Comment by sloesel** [comment]
Hi Benji - we will provide answers to your question shortly.

Stephane

**Comment by charlthibault** [comment]
Hi @benji07, 
you can ether give all your query parameters in an array like you show or add one by one using AfsQuery methods (add_filter, set_lang, etc.): see example [here](https://github.com/antidot/PHP_API/blob/master/doc/data/raw_example.php).

For filter parameter, the key should be the facet id (defined at indexation time, see our [documentation](http://doc.antidot.net/book#!book;uri=30d1a33232d9959b0ade5133cda1045d;breadcrumb=b77062d141d7db5f5626ff2730595007-82aa9ed728cbdbdeb4d8934ac522eef7-acfda6ee5762b2a8a7317b08c28e57ee-ed01a0d019115214331349c9ffbac248) for more details) and the value a list of values to filter on (you can filter on multiple values, that is why you should provide an array of values).

Filter values are typed, so you should provide values with good type. In your case, this is a 'string' type, so you should provide values with quotes.

You can retrieve indexed facets by using [introspection](https://github.com/antidot/PHP_API/blob/master/AFS/SEARCH/Afs_introspection.php). Here is an example:

```php
$search = new AfsSearch('your_server', 1, AfsServiceStatus::STABLE);

$introspector = new AfsIntrospection($search);
$metadata = $intropsector->get_all_metadata();

foreach ($metadata as $meta) { // $meta => AfsMetadataHelper
    foreach ($meta->get_facets_and_filters_info() as $info) { // $info: AfsFacetInfoHelper
        print $info->get_id() . ': ' . $info->get_type() . '\n';
    }
}
```

**Comment by benji07** [comment]
Yes, but this should work:

```
'store' => ['myStoreId']
```

**Comment by sloesel** [comment]
@benji07 - you need the double quotes to filter on the literal string value "myStoreId" and not the identifier called myStoreId. In AFS web service syntax this would be expressed as:
```
afs:filter=store="myStoreId"
```
and not
```
afs:filter=store=myStoreId
```

**Comment by benji07** [comment]
@sloesel the php api should abstract this, I should never write this ugly thing

**Comment by sloesel** [comment]
@benji07 I agree that this would be a nice improvement. This could be done as @charlthibault said using introspection. But for now this feature is not available :-)
